name: Quality and Coverage Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black
        run: black .github/scripts/ --check

      - name: Run pylint
        run: pylint .github/scripts/

      - name: Run mypy
        run: mypy .github/scripts/

      - name: Run bandit
        run: bandit -r .github/scripts/

      - name: Run tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pytest .github/scripts/test_update_dx.py -v
